name: Check this flake
on:
  pull_request:
    paths-ignore:
      - 'README.*'
  push:
    branches:
      - master
    paths-ignore:
      - 'README.*'
  workflow_dispatch:
jobs:
  check:
    uses: ./.github/workflows/check.yml
